# Generated by Django 5.2.3 on 2025-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/", verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1.png", "预设头像1"),
                    ("2.png", "预设头像2"),
                    ("3.png", "预设头像3"),
                    ("4.png", "预设头像4"),
                    ("5.png", "预设头像5"),
                ],
                max_length=32,
                null=True,
                verbose_name="预设头像",
            ),
        ),
    ]
