# Generated by Django 5.2.3 on 2025-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_hours", models.FloatField(verbose_name="每日学习时长")),
                ("homework_done", models.BooleanField(verbose_name="作业完成情况")),
                ("interaction_count", models.IntegerField(verbose_name="课堂互动次数")),
                ("test_score", models.FloatField(verbose_name="测试成绩")),
                ("date", models.DateField(verbose_name="日期")),
            ],
        ),
    ]
