# Generated by Django 5.2.3 on 2025-06-22 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(blank=True, max_length=32, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=8, null=True)),
                ("study_hours_per_day", models.FloatField(blank=True, null=True)),
                ("social_media_hours", models.FloatField(blank=True, null=True)),
                ("netflix_hours", models.FloatField(blank=True, null=True)),
                ("part_time_job", models.BooleanField(blank=True, null=True)),
                ("attendance_percentage", models.FloatField(blank=True, null=True)),
                ("sleep_hours", models.FloatField(blank=True, null=True)),
                (
                    "diet_quality",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("exercise_frequency", models.IntegerField(blank=True, null=True)),
                (
                    "parental_education_level",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "internet_quality",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("mental_health_rating", models.IntegerField(blank=True, null=True)),
                (
                    "extracurricular_participation",
                    models.BooleanField(blank=True, null=True),
                ),
                ("exam_score", models.FloatField(blank=True, null=True)),
                ("predict_result", models.FloatField(blank=True, null=True)),
                ("predict_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩预测记录",
                "verbose_name_plural": "成绩预测记录",
                "ordering": ["-predict_time"],
            },
        ),
    ]
